baseURL = "/"
languageCode = "en-us"
title = "The DIFY"
theme = "difyTheme"


[params]
    author = "Andrew M McCall"
    description = "Dify Store is an arts and crafts blog and e-commerce store front."
    opengraphdefault = "/images/logo.png"
    imgAltDefault = "/images/logo.png"


[[params.social]]
name = "Facebook"
url = "https://www.facebook.com/thedify"
icon = "fa fa-facebook fa-sm"

[[params.social]]
name = "Instagram"
url = "https://www.instagram.com/thedify"
icon = "fa fa-instagram fa-sm"

[[params.social]]
name = "TikTok"
url = "https://www.tiktok.com/@thedify"
image = "/images/tiktok-icon-50x50.png"



[markup.goldmark.renderer]
    unsafe = true

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 90
[[related.indices]]
  name = 'date'
  weight = 100
    
[taxonomies]
  category = 'categories'
  tag = 'tags'



[menu]
[[menu.main]]
identifier = '/'
name = 'Home'
url = '/'
weight = -210


[[menu.main]]
identifier = 'about-us'
name = "About Us"
url = '/about-us/'
weight = -180


[[menu.main]]
identifier = 'contact-us'
name = 'Contact Us'
url = '/contact-us/'
weight = -190

[[menu.main]]
identifier = 'services'
name = 'Services'
url = '/services/'

[[menu.privacy]]
identifier = 'privacy-policy'
name = 'Privacy Policy'
url = '/privacy-policy/'
weight = 0

[[menu.privacy]]
identifier = 'cookie-policy'
name = 'Cookie Policy'
url = '/cookie-policy/'
weight = 0

[[menu.privacy]]
identifier = 'terms-and-conditions'
name = 'Terms and Conditions'
url = '/terms-and-conditions/'
weight = 20

[[menu.privacy]]
identifier = 'dmca'
name = 'DMCA Copyright'
url = '/dmca/'
weight = 20

